---
- hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become_user: root

  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
