---
- hosts: all
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Optional: suppress Python warning
  tasks:

    - name: Check if node is reachable
      shell: "echo 'reachable'"
      delegate_to: "{{ item }}"
      register: node_status
      ignore_errors: true
      loop: "{{ ansible_play_hosts }}"
      changed_when: false
      run_once: true

    - name: Set fact for reachable nodes
      set_fact:
        reachable_nodes: >-
          {{ node_status.results
             | selectattr('unreachable', 'undefined')
             | selectattr('skipped', 'undefined')
             | map(attribute='item')
             | list }}

    - name: Debug reachable nodes
      debug:
        var: reachable_nodes

    - name: Install updates on reachable nodes
      apt:
        update_cache: yes
        upgrade: dist
      become: yes
      loop: "{{ reachable_nodes }}"
      loop_control:
        loop_var: target_node
      delegate_to: "{{ target_node }}"

    - name: Reboot reachable nodes
      reboot:
      become: yes
      loop: "{{ reachable_nodes }}"
      loop_control:
        loop_var: target_node
      delegate_to: "{{ target_node }}"
