---
- hosts: all
  gather_facts: false
  tasks:
    - name: Check if node is reachable
      shell: "echo 'reachable'"
      delegate_to: "{{ item }}"
      register: node_status
      ignore_errors: true
      loop: "{{ ansible_play_hosts }}"
      changed_when: false
      run_once: true

    - name: Update Proxmox on online nodes
      include_tasks: update_and_reboot.yml
      when: node_status.results[loop.index0].skipped is not defined
      loop: "{{ ansible_play_hosts }}"
      loop_control:
        loop_var: item
      delegate_to: "{{ item }}"
